[project]
name = "scope-pipeline"
version = "0.1.1"
requires-python = "==3.12.*"
dependencies = [
    "ai-runner[realtime]",
    "daydream-scope",
]

[project.scripts]
scope-runner = "scope_runner.main:main"

[tool.uv.sources]
ai-runner = { git = "https://github.com/livepeer/ai-runner.git", rev = "b1d89d34fd5c08591c969c63e4be857d137c7193", subdirectory = "runner" }
# ai-runner = { path = "../ai-runner/runner" }
daydream-scope = { git = "https://github.com/daydreamlive/scope.git", rev = "7ff0e6dfbaaf8852483d2d8dde66daca4ff460ed" }

[tool.uv]
package = true
# Let scope dictate fastapi version (ai-runner pins 0.115.6, scope needs >=0.116.1)
override-dependencies = ["fastapi>=0.116.1"]

[tool.setuptools.packages.find]
where = ["src"]
